version: "3"
services:
  api:
    container_name: fastify-typescript
    platform: osx,windows/amd64,linux/arm64/v8
    ports:
      - 8003:8003
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./:/app